version: '3'
services:
  jackett:
    image: "linuxserver/jackett"
    container_name: jackett_instance
    ports:
      - 9117:9117
    restart: always
    environment:
      - PGID=1000
      - PUID=1000    
    volumes:
      - <config-path>:/config
      - <download-path>:/downloads 
      - /etc/localtime:/etc/localtime:ro
  transmission_vpn:
    image: "haugene/transmission-openvpn"
    container_name: transmission_vpn
    cap_add: 
      - NET_ADMIN
    devices: 
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - 9091:9091
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - OPENVPN_PROVIDER=
      - OPENVPN_CONFIG=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - LOCAL_NETWORK=
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_RPC_PASSWORD=sample_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <transmission-data-path>:/data

